name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.1
      - name: install
        run: cd ./client && npm install && npm install -g vsce && vsce package
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: "spoon-language-server.*.vsix"
          path: "./client"
      
